### ISSUE TITLE
Error while loading URL (technique/d3f:ApplicationHardening.json)

### ISSUE THREAD

**Issue by joaovarelas** [mitre/d3fend#1]
Hello,

I am receiving the following error while trying to load the URL:

https://d3fend.mitre.org/technique/d3f:ApplicationHardening

`500 - JSON.parse: unexpected character at line 1 column 1 of the JSON data`

The page fails to load after launching the exception.

Root cause: the following resource is not found https://d3fend.mitre.org/technique/d3f:ApplicationHardening.json

I believe the dropdown boxes should distinguish between `/technique` and `/group` so that the correct resource is loaded.

![image](https://user-images.githubusercontent.com/6439813/123104377-cb571c80-d42e-11eb-98bc-a92f3211fbbc.png)

Regards

**Comment by netfl0** [comment]
Thank you for your submission, we will get this fixed.

**Comment by netfl0** [comment]
Fixed in version 0.9.3-BETA-1.
