### ISSUE TITLE
Unable to clone repo to my Windows box

### ISSUE THREAD

**Issue by tonyennis** [mitre/d3fend#12]
using Github Desktop. Tried it to two different drives, failed in the same place both times. Might be a file name issue on Windoze.  I checked the folder; there are no files in it.

![image](https://github.com/d3fend/d3fend/assets/7684843/2b8ed973-0b9c-4bf8-b537-4dc9dd17a589)

I am thinking it has something to do with the colons in certain filenames. I don't know if these are valid on Windows or not.  I cloned this with the command line, so github desktop doesn't seem to be part of the problem.

![image](https://github.com/d3fend/d3fend/assets/7684843/ea2cf4bd-dfb8-433e-847c-29f225defc98)

**Comment by netfl0** [comment]
I would recommend using a *nix environment on windows:
* git for windows provides a shell, not sure if that will work 
* WSL will work
* VM with a shared folder

We are going to always keep the : in the name because that is standard OWL notation.

**Comment by tonyennis** [comment]
I suppose you've made your decision, but using an odd technology (owl) which alienates 90% of the computers on the planet seems short-sighted.

**Comment by netfl0** [comment]
@tonyennis  We're open to suggestions here, the API is intended be served over HTTP from a *nix web server. 

We have lots of folks using the current structure and we didn't want to break that.

**Comment by tonyennis** [comment]
You're doing good work, no one should want to derail that.  Perhaps we can create another project that uses your project as input and produces more consumable/standard output.  Where "we" may or not be me, I need to think about the time commitment.

**Comment by tonyennis** [comment]
My use case is _very_ different from what I see here.

FYI - I am not a Windows-lover. Or hater.  This really isn't about Windows at all since i use Unix at work. But I use Windows at home and I couldn't even clone the repo without errors.  

Anyway, enough of my noise on a closed ticket.
