### ISSUE TITLE
Broken extraction in \GitHub\d3fend\resources\d3fend-full-mappings.json ?

### ISSUE THREAD

**Issue by tonyennis** [mitre/d3fend#13]
F:\GitHub\d3fend\resources\d3fend-full-mappings.json  makes me weep

![image](https://github.com/d3fend/d3fend/assets/7684843/1c3b5557-bf25-4a99-adac-b1239558b8c0)

**Comment by netfl0** [comment]
Ah good find. Those files are deprecated were not deleted for some reason, I will delete them, here is the new correct path:

https://d3fend.mitre.org/api/ontology/inference/d3fend-full-mappings.json

<img width="1005" alt="image" src="https://github.com/d3fend/d3fend/assets/544260/2f51f27a-1ded-46ae-bfc6-3e1a1d59b876">
