### ISSUE TITLE
Integrate definitions

### ISSUE THREAD

**Issue by ioggstream** [mitre/d3fend#2]
## Question

Should the Ontology contain  definitions for concepts such as "countermeasure" ?

**Comment by netfl0** [comment]
Yes, absolutely. The next release will have this defined on d3f:DefensiveTechnique.

**Comment by ioggstream** [comment]
Is it developed on GitHub?

**Comment by netfl0** [comment]
The ontology pipeline is not open source at this time. We are working to change that.

The new release is now available. Please feel free to send feedback on or contribute new definitions.

**Comment by ioggstream** [comment]
Thanks @petekalo, I really hope that a wider community can contribute to this interesting work! :)

**Comment by ioggstream** [comment]
The repo is here https://github.com/d3fend/d3fend-ontology/
