### ISSUE TITLE
Site Navigation in Resources section can be confusing

### ISSUE THREAD

**Issue by watgh** [mitre/d3fend#4]
The javascript for the Resources page provides some great capability.  However, the generated links are sometimes confusing or produce unexpected results.

For example, attack mitigations page is dynamically generated by the javascript, but the generated link cannot be shared.  So one can navigate to /resources, but when you go to the Mappings section and click on "attack-mitigations" the resulting URL is https://d3fend.mitre.org/mappings/attack-mitigations, but this link cannot be shared.  Trying to use the link directly results in a 404.
Similarly, navigating into elements in the table can have mixed results if a user tries to "go back" a page.

We really like the mitigations page and want to be able to point users to it from our other tools.  If we come up with a solution, we'll suggest it.  Thanks!

**Comment by netfl0** [comment]
Thank you, yes we are tracking that bug internally. It has to do with how the site is exported to static and we should have a fix soon.

Once we open source the tooling issue tracking easier to coordinate as well.

**Comment by netfl0** [comment]
This was fixed in the June release.
