### ISSUE TITLE
Correlating cybersecurity functions 

### ISSUE THREAD

**Issue by ioggstream** [mitre/d3fend#6]
## Question

how can I correlate the 5 cybersecurity functions https://www.nist.gov/cyberframework/online-learning/five-functions to d3fend entities?

For example:

nist:Detect iso:related d3f:Detect
.
nist:Protect iso:related [
    d3f:Harden,
    d3f:Isolate
.
nist:Respond iso:related d3f:Evict
.

In d3f, functions such as Identify (asset identification) and Respond doesn't seem to be classified (though d3f:Evict is probably related), while it seems that Recover is currently out of scope.

**Comment by netfl0** [comment]
We are going to be addressing the identify, respond, and restore aspects with some new top-levels soon. Yes Evict is related to Respond.

Please note the ontology repo is now available here:

https://github.com/d3fend/d3fend-ontology/
