### ISSUE TITLE
Taxonomy for Source Code Hardening Techniques

### ISSUE THREAD

**Issue by ioggstream** [mitre/d3fend#7]
## Question

-     d3f:M1013  says "A future release of D3FEND will define a taxonomy of Source Code Hardening Techniques." 

I am willing to support this work. Probably it can integrate SAMM2 work...

**Comment by netfl0** [comment]
Excellent, lets track this issue here:

https://github.com/d3fend/d3fend-ontology/

Also, feel free to join our slack here:

https://join.slack.com/t/mitre-d3fend/shared_invite/zt-108eicnoj-fpZPD9EFNtuMNDVrlRWQlA
